// Generated by CoffeeScript 1.9.0
var App, inflector;

App = Ember.Application.create({
  rootElement: '#emberApp'
});

App.Router.map(function() {
  return this.resource('root', {
    path: '/'
  }, function() {
    this.resource('activity', {
      path: '/activity/:imgur_id'
    });
    this.resource('watches', {
      path: '/watches'
    });
    return this.resource('about', {
      path: '/about'
    });
  });
});

App.ActivityRoute = Ember.Route.extend({
  model: function(params) {
    console.log('model', params);
    return this.store.find('watch', {
      imgur_id: params.imgur_id
    });
  },
  afterModel: function(model, transition) {
    var filter, imgurId;
    console.log('afterModel', model.get('firstObject.imgurId'));
    imgurId = model.get('firstObject.imgurId');
    filter = this.store.filter('activity', {
      imgur_id: imgurId
    }, function(activity) {
      return activity.get('imgurId') === imgurId;
    });
    this.controllerFor('activities').set('model', filter);
    return filter;
  },
  serialize: function(model) {
    return {
      imgur_id: model.get('firstObject.imgurId')
    };
  },
  setupController: function(controller, model) {
    this._super(controller, model);
    return this.controller.set('model', model.get('firstObject'));
  }
});

App.WatchesRoute = Ember.Route.extend({
  model: function() {
    return this.store.find('watch');
  }
});

App.AboutRoute = Ember.Route.extend({});

App.ApplicationAdapter = DS.ActiveModelAdapter.extend({
  host: 'http://localhost:3000',
  namespace: 'api'
});

inflector = Ember.Inflector.inflector;

inflector.irregular('activity', 'activities');
