// Generated by CoffeeScript 1.9.0
var App, inflector;

App = Ember.Application.create({
  rootElement: '#emberApp'
});

App.Router.map(function() {
  return this.resource('root', {
    path: '/'
  }, function() {
    this.resource('activity', {
      path: '/activity/:imgur_id'
    });
    this.resource('watches', {
      path: '/watches'
    });
    return this.resource('about', {
      path: '/about'
    });
  });
});

App.ActivityRoute = Ember.Route.extend({
  model: function(params) {
    var promises;
    promises = [];
    promises.push(this.store.find('watch', {
      imgur_id: params.imgur_id
    }));
    promises.push(this.store.find('activity', {
      imgur_id: params.imgur_id
    }));
    return Ember.RSVP.all(promises);
  },
  serialize: function(model) {
    return {
      imgur_id: model.get('imgurId')
    };
  },
  setupController: function(controller, model) {
    this._super(controller, model);
    this.controller.set('model', model.get('firstObject'));
    return this.controllerFor('activities').set('model', model.get('lastObject'));
  }
});

App.WatchesRoute = Ember.Route.extend({
  model: function() {
    return this.store.find('watch');
  }
});

App.AboutRoute = Ember.Route.extend({});

App.ApplicationAdapter = DS.ActiveModelAdapter.extend({
  host: 'http://localhost:3000',
  namespace: 'api',
  ajax: function(url, type, hash) {
    hash = hash || {};
    hash.cache = false;
    return this._super(url, type, hash);
  }
});

inflector = Ember.Inflector.inflector;

inflector.irregular('activity', 'activities');
