// Generated by CoffeeScript 1.9.0
App.WatchesController = Ember.ArrayController.extend({
  actions: {
    showActivity: function(watch) {
      console.log('showActivity', watch);
      return this.transitionToRoute('activity', watch);
    }
  }
});

App.AddWatchComponent = Ember.Component.extend({
  errMsg: null,
  val: null,
  store: (function() {
    return this.container.lookup('store:main');
  }).property(),
  checkImgur: function(id) {
    return console.log('checkImgur');
  },
  checkStore: function(id) {
    return this.get('store').find('watch', {
      img_id: id
    }).then((function(_this) {
      return function(records) {
        if (records.length) {
          return _this.set('errMsg', 'ID already exists');
        } else {
          return _this.checkImgur(id);
        }
      };
    })(this));
  },
  validate: function() {
    var id;
    id = this.get('val');
    if (!id || !id.length) {
      this.set('errMsg', 'Please enter a valid imgur ID');
      return false;
    }
    return this.checkStore(id);
  },
  actions: {
    add: function() {
      return console.log(this.validate());
    }
  }
});
