// Generated by CoffeeScript 1.9.0
App.ImgurApiController = Ember.Controller.extend({
  get: function(id) {
    return $.ajax({
      url: 'https://api.imgur.com/3/gallery/image/' + id,
      headers: {
        Authorization: 'Client-ID b37988f15bb617f'
      }
    });
  }
});

App.WatchesController = Ember.ArrayController.extend({
  needs: ['imgurApi'],
  errMsg: null,
  val: null,
  reset: function() {
    return this.setProperties({
      errMsg: null,
      val: null
    });
  },
  _add: function(imgurObj) {
    var newWatch, now, nowActivity, uploaded;
    console.log('_add', imgurObj);
    now = new Date();
    uploaded = new Date(imgurObj.datetime * 1000);
    newWatch = this.store.createRecord('watch', {
      imgurId: imgurObj.id,
      started: now,
      uploaded: uploaded
    });
    newWatch.save();
    nowActivity = this.store.createRecord('activity', {
      comments: imgurObj.comment_count,
      datetime: now,
      downs: imgurObj.downs,
      imgurId: imgurObj.id,
      score: imgurObj.score,
      ups: imgurObj.ups,
      views: imgurObj.views
    });
    nowActivity.save();
    return this.reset();
  },
  checkImgur: function(id) {
    console.log('checkImgur', id);
    return this.get('controllers.imgurApi').get(id).done((function(_this) {
      return function(response) {
        console.log('done', response);
        if (response.success) {
          return _this._add(response.data);
        }
      };
    })(this)).fail((function(_this) {
      return function(jqXHR, textStatus) {
        console.log('fail', jqXHR, textStatus);
        return _this.set('errMsg', 'Invalid ID');
      };
    })(this));
  },
  checkStore: function(id) {
    return this.store.find('watch', {
      img_id: id
    }).then((function(_this) {
      return function(records) {
        if (records.length) {
          return _this.set('errMsg', 'ID already exists');
        } else {
          return _this.checkImgur(id);
        }
      };
    })(this));
  },
  validate: function() {
    var id;
    id = this.get('val');
    if (!id || !id.length) {
      this.set('errMsg', 'Please enter a valid imgur ID');
      return false;
    }
    return this.checkStore(id);
  },
  actions: {
    add: function() {
      return console.log(this.validate());
    },
    showActivity: function(watch) {
      console.log('showActivity', watch.get('imgurId'));
      return this.transitionToRoute('activity', [watch]);
    },
    "delete": function(watch) {
      console.log('delete', watch);
      watch.deleteRecord();
      return watch.save();
    }
  }
});

App.ActivityView = Ember.View.extend({
  didInsertElement: function() {
    console.log('activityView didInsertElement');
    return this.initD3();
  },
  activitiesDidChange: (function() {
    return console.log('activitiesDidChange');
  }).observes('controller.activities.length'),
  initD3: function() {
    var activities, data, dataStr, height, line, margin, parseDatetime, svg, width, x, xAxis, y, yAxis;
    margin = {
      top: 20,
      right: 20,
      bottom: 30,
      left: 100
    };
    width = 960 - margin.left - margin.right;
    height = 300 - margin.top - margin.bottom;
    x = d3.time.scale().range([0, width]);
    y = d3.scale.linear().range([height, 0]);
    xAxis = d3.svg.axis().scale(x).orient("bottom");
    yAxis = d3.svg.axis().scale(y).orient("left");
    svg = d3.select(".activity .chart").append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
    activities = this.get('controller.activities');
    dataStr = activities.get('viewsDataStr');
    parseDatetime = d3.time.format('%0m/%0d/%Y %0I:%M:%S %p').parse;
    data = d3.csv.parse(dataStr, function(d) {
      return {
        datetime: parseDatetime(d.datetime),
        views: +d.views
      };
    });
    x.domain(d3.extent(data, function(d) {
      return d.datetime;
    }));
    y.domain(d3.extent(data, function(d) {
      return d.views;
    }));
    svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);
    svg.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", 6).attr("dy", ".71em").style("text-anchor", "end").text("views");
    line = d3.svg.line().x(function(d) {
      return x(d.datetime);
    }).y(function(d) {
      return y(d.views);
    });
    return svg.append("path").datum(data).attr("class", "line").attr("d", line);
  }
});

App.ActivityController = Ember.Controller.extend({
  needs: ['activities'],
  activities: Ember.computed.alias('controllers.activities')
});

App.ActivitiesController = Ember.ArrayController.extend({
  viewsDataStr: (function() {
    var dataStr;
    dataStr = 'datetime,views\n';
    this.sortBy('datetime').forEach(function(item) {
      dataStr += (item.get('datetime')).toLocaleString().replace(',', '') + ',' + (item.get('views')) + '\n';
      return null;
    });
    return dataStr;
  }).property('@each')
});

App.SocketController = Ember.Controller.extend({
  init: function() {
    var socket;
    this._super();
    socket = io.connect('http://localhost:3000');
    socket.on('new_activity', (function(_this) {
      return function(data) {
        console.log('new_activity', typeof data, data);
        return _this.store.push('activity', _this.store.normalize('activity', data));
      };
    })(this));
    return this.set('socket', socket);
  }
});
