// Generated by CoffeeScript 1.9.0
App.Watch = DS.Model.extend({
  activities: DS.hasMany('activity'),
  imgId: DS.attr('string'),
  started: DS.attr('date'),
  uploaded: DS.attr('date')
});

App.Activity = DS.Model.extend({
  comments: DS.attr('number'),
  datetime: DS.attr('date'),
  downs: DS.attr('number'),
  score: DS.attr('number'),
  ups: DS.attr('number'),
  views: DS.attr('number'),
  watch: DS.belongsTo('watch')
});
