// Generated by CoffeeScript 1.9.0
(function() {
  var compileTemplates, compiler, fs, path;

  fs = require('fs');

  path = require('path');

  compiler = require('./js/libs/ember-template-compiler-1.10.0');

  compileTemplates = function() {
    var filename, filenames, input, name, output, template, _i, _len;
    console.log('compiling templates...');
    output = '';
    filenames = fs.readdirSync('hbs').filter(function(filename) {
      return /hbs/.test(filename);
    });
    for (_i = 0, _len = filenames.length; _i < _len; _i++) {
      filename = filenames[_i];
      template = fs.readFileSync('hbs/' + filename).toString();
      input = compiler.precompile(template).toString();
      name = path.parse(filename).name;
      output += "Ember.TEMPLATES['" + name + "'] = Ember.Handlebars.template(" + input + ");";
    }
    return fs.writeFileSync('templates.js', output, {
      encoding: 'utf8'
    });
  };

  fs.watch('hbs', function(event, filename) {
    console.log('event', event, 'filename', filename);
    console.log(/hbs/.test(filename));
    if (event === 'change' && /hbs/.test(filename)) {
      return compileTemplates();
    }
  });

}).call(this);
