// Generated by CoffeeScript 1.9.0
(function() {
  var http, interval, options, update;

  http = require('http');

  options = {
    method: 'put',
    path: '/api/watches/update',
    port: 3000
  };

  update = function() {
    var req;
    console.log('update', Date.now());
    req = http.request(options, function(res) {
      return console.log('request success');
    });
    req.on('error', function(e) {
      return console.log('problem with request: ' + e.message);
    });
    return req.end();
  };

  update();

  interval = setInterval(function() {
    return update();
  }, 60 * 1000);

  console.log('end');

}).call(this);
