// Generated by CoffeeScript 1.9.0
(function() {
  var http, options, req, update;

  http = require('http');

  options = {
    method: 'put',
    path: '/api/watches/update',
    port: 3000
  };

  update = function() {
    console.log('update', Date.now());
    return http.request(options, function(res) {
      return console.log('res', res);
    });
  };

  req = update();

  req.on('error', function(e) {
    return console.log('problem with request: ' + e.message);
  });

  console.log('end');

}).call(this);
